### ISSUE TITLE
有没有一键部署的？

### ISSUE THREAD

**Issue by iambonboncat** [lzqwebsoft/heroku-blog#2]
有没有一键部署的？

**Comment by lzqwebsoft** [comment]
没有写一键部署的脚本，而且这个项目从16年开始就转为虚拟主机了，所以heroku的部分一直就弃置没有再更新过，建设弄个虚拟主机吧，一年也才20刀：[https://www.zhujiceping.com/23509.html](https://www.zhujiceping.com/23509.html),heroku免费很慢的～～～～
