### ISSUE TITLE
提一个新手问题

### ISSUE THREAD

**Issue by hiEmin** [lzqwebsoft/heroku-blog#3]
数据库连接中的
:3306/heroku_blog_db?characterEncoding=UTF-8&serverTimezone=GMT%2B8

在databaseDesign中没有看到 heroku_blog_db 这个表呀

**Comment by lzqwebsoft** [comment]
哦哦，数据库要自己先创建一下：
```sql
CREATE DATABASE heroku_blog_db  CHARACTER SET utf8 COLLATE utf8_general_ci;
```
然后直接运行
```
mvn spring-boot:run
```
由于配置了hibernate的：`hibernate.hbm2ddl.auto`为update,则表结构则自动根据xml定义文件生成。
> hibernate.hbm2ddl.auto Automatically validates or exports schema DDL to the database when the SessionFactory is created. With create-drop, the database schema will be dropped when the SessionFactory is closed explicitly.
e.g. validate | update | create | create-drop

1. [文档](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl)
2. [配置](https://github.com/lzqwebsoft/heroku-blog/blob/master/src/main/resources/spring-database-context.xml)

如果一切正常的话，再根据`README`中的说明跑下初始sql脚本，完成程序的一些初始数据的导入。

哈哈，听起来好像很复杂啊~enjoy!😁

**Comment by hiEmin** [comment]
成功部署了，谢啦ヾ(o′▽`o)ノ°°

**Comment by lzqwebsoft** [comment]
有问题欢迎交流！
